"""adchange datetime clmn to string

Revision ID: 8205ca3ac04c
Revises: bfb23c22a907
Create Date: 2025-01-31 00:26:49.764043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8205ca3ac04c'
down_revision = 'bfb23c22a907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lendings', schema=None) as batch_op:
        batch_op.alter_column('BorrowDate',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('ReturnDate',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lendings', schema=None) as batch_op:
        batch_op.alter_column('ReturnDate',
               existing_type=sa.String(length=80),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('BorrowDate',
               existing_type=sa.String(length=80),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
