"""initial migration

Revision ID: bfb23c22a907
Revises: 
Create Date: 2025-01-30 08:12:22.777526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb23c22a907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=80), nullable=False),
    sa.Column('Author', sa.String(length=80), nullable=False),
    sa.Column('NumberOfBooks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('ClassName', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Student_id', sa.Integer(), nullable=True),
    sa.Column('Book_id', sa.Integer(), nullable=True),
    sa.Column('BorrowDate', sa.DateTime(), nullable=False),
    sa.Column('ReturnDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['Book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['Student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lendings')
    op.drop_table('students')
    op.drop_table('books')
    # ### end Alembic commands ###
